-- sql/schemas/01_staging.sql
-- Staging layer DDL — mirrors raw source with minimal cleaning

CREATE TABLE IF NOT EXISTS stg_listings_raw (
    id                              INTEGER PRIMARY KEY,
    listing_url                     TEXT,
    name                            TEXT,
    description                     TEXT,
    neighbourhood_cleansed          TEXT,
    neighbourhood_group_cleansed    TEXT,
    latitude                        REAL,
    longitude                       REAL,
    property_type                   TEXT,
    room_type                       TEXT,
    accommodates                    INTEGER,
    bathrooms                       REAL,
    bedrooms                        REAL,
    beds                            REAL,
    price                           REAL,
    minimum_nights                  INTEGER,
    maximum_nights                  INTEGER,
    number_of_reviews               INTEGER,
    number_of_reviews_ltm           INTEGER,
    review_scores_rating            REAL,
    review_scores_cleanliness       REAL,
    review_scores_location          REAL,
    review_scores_value             REAL,
    instant_bookable                BOOLEAN,
    host_id                         INTEGER,
    host_name                       TEXT,
    host_since                      TEXT,
    host_is_superhost               BOOLEAN,
    host_listings_count             INTEGER,
    host_total_listings_count       INTEGER,
    calculated_host_listings_count  INTEGER,
    availability_30                 INTEGER,
    availability_60                 INTEGER,
    availability_90                 INTEGER,
    availability_365                INTEGER,
    last_review                     TEXT,
    reviews_per_month               REAL
);

CREATE TABLE IF NOT EXISTS stg_listings_clean (
    -- Same columns as raw, with cleaned types and filtered rows
    -- Built by transform.py layer 1
    id                              INTEGER PRIMARY KEY,
    listing_url                     TEXT,
    name                            TEXT,
    neighbourhood_cleansed          TEXT,
    borough                         TEXT,
    latitude                        REAL,
    longitude                       REAL,
    property_type                   TEXT,
    room_type                       TEXT,
    accommodates                    INTEGER,
    bedrooms                        REAL,
    beds                            REAL,
    bathrooms                       REAL,
    price                           REAL,
    minimum_nights                  INTEGER,
    maximum_nights                  INTEGER,
    number_of_reviews               INTEGER,
    number_of_reviews_ltm           INTEGER,
    review_scores_rating            REAL,
    review_scores_cleanliness       REAL,
    review_scores_location          REAL,
    review_scores_value             REAL,
    instant_bookable                INTEGER,
    host_id                         INTEGER,
    host_name                       TEXT,
    host_since                      TEXT,
    host_is_superhost               INTEGER,
    host_listings_count             INTEGER,
    calculated_host_listings_count  INTEGER,
    availability_30                 INTEGER,
    availability_60                 INTEGER,
    availability_90                 INTEGER,
    availability_365                INTEGER,
    last_review                     TEXT,
    reviews_per_month               REAL
);
